env:
  es2021: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules:
  strict:
    - error
  no-undef:
    - error
  no-unreachable-loop:
    - error
  array-callback-return:
    - error
  consistent-return:
    - error
  curly:
    - error
    - multi-line
    - consistent
  default-case-last:
    - error
  default-param-last:
    - error
  dot-location:
    - error
    - property
  dot-notation:
    - error
  eqeqeq:
    - error
    - always
  grouped-accessor-pairs:
    - error
  no-constructor-return:
    - error
  no-else-return:
    - error
  no-eq-null:
    - error
  no-eval:
    - error
  no-extend-native:
    - error
  no-extra-label:
    - error
  no-floating-decimal:
    - error
  no-invalid-this:
    - error
  no-labels:
    - error
  no-lone-blocks:
    - error
  no-loop-func:
    - error
  no-multi-spaces:
    - error
  no-multi-str:
    - error
  no-new:
    - error
  no-new-func:
    - error
  no-new-wrappers:
    - error
  no-nonoctal-decimal-escape:
    - error
  no-octal-escape:
    - error
  no-proto:
    - error
  no-return-assign:
    - error
  no-return-await:
    - error
  no-self-compare:
    - error
  no-sequences:
    - error
  no-throw-literal:
    - error
  no-useless-concat:
    - error
  no-useless-return:
    - error
  no-void:
    - error
  no-label-var:
    - error
  no-undef-init:
    - error
  array-bracket-spacing:
    - error
    - always
  array-element-newline:
    - error
    - consistent
  block-spacing:
    - error
    - always
  brace-style:
    - error
  comma-spacing:
    - error
    - before: false
      after: true
  comma-style:
    - error
    - last
  computed-property-spacing:
    - error
    - never
  eol-last:
    - error
    - always
  func-call-spacing:
    - error
    - never
  func-style:
    - error
    - expression
  function-call-argument-newline:
    - error
    - consistent
  implicit-arrow-linebreak:
    - error
    - beside
  indent:
    - error
    - 2
  key-spacing:
    - error
  keyword-spacing:
    - error
  linebreak-style:
    - error
    - unix
  lines-between-class-members:
    - error
    - always
  max-len:
    - error
    - code: 80
  new-cap:
    - error
  new-parens:
    - error
  no-lonely-if:
    - error
  no-mixed-operators:
    - error
  no-multi-assign:
    - error
  no-multiple-empty-lines:
    - error
  no-negated-condition:
    - error
  no-trailing-spaces:
    - error
  no-unneeded-ternary:
    - error
  no-whitespace-before-property:
    - error
  nonblock-statement-body-position:
    - error
    - beside
  object-curly-spacing:
    - error
    - always
  one-var:
    - error
    - never
  quote-props:
    - error
    - as-needed
  quotes:
    - error
    - single
  semi:
    - error
    - always
  semi-spacing:
    - error
  semi-style:
    - error
    - last
  space-before-blocks:
    - error
  space-before-function-paren:
    - error
    - never
  space-infix-ops:
    - error
  switch-colon-spacing:
    - error
  template-tag-spacing:
    - error
  arrow-body-style:
    - error
    - as-needed
  arrow-spacing:
    - error
  no-confusing-arrow:
    - error
  no-duplicate-imports:
    - error
  no-var:
    - error
  prefer-arrow-callback:
    - error
  prefer-const:
    - error
  prefer-spread:
    - error
  prefer-template:
    - error
  rest-spread-spacing:
    - error
