export { HomePage } from './home/home';
export { ProfilePage } from './profile/profile';
export { TasksPage } from './tasks/tasks';
export { Order as OrderPage } from './orders/order';
export { Orders as OrdersPage } from './orders/orders';
export { Acts as ActsPage } from './acts/acts';
export { TestPage } from './test/test';
export { FormOrders as FormOrdersPage } from './form-orders/form-orders';
export { FormOrder as FormOrderPage } from './form-orders/form-order';
export { ManualPage } from './manual/manual-page';
export { ManualMOC } from './manual/manuals-moc';
export { PriceOrder as PriceOrderPage } from './price-orders/price-order';
export { PriceOrders as PriceOrdersPage } from './price-orders/price-orders';
export { EPPage } from './ep/ep';
export { EPMainForm } from './ep-main/ep-main-OTK';
export { EPTachograph } from './ep-main/tachograph/ep-tachograph';
export { Diotrade } from './ep-main/diotrade/diotrade';
export { EpCO2Form } from './ep-main/CO2/ep-CO2';
export { EKMT } from './ep-main/EKMT/ekmt';
export { LabReport as LabReportPage } from './lab-reports/lab-report';
export { LabReports as LabReportsPage } from './lab-reports/lab-reports';
export { PolicyPage } from './insurance-policy/table/policy';
export { PolicyCard } from './insurance-policy/card-policy/policyCard';
export { PolicyNew } from './insurance-policy/new-policy/policyNew';
export { Dashboard as DashboardPage } from './dashboard/dashboard';
export { ContractOffer } from './contract-offer/contract-offer';
export { ImportCarsPage } from './import-cars';
