export const manuals = [
  {
    pageId: '1',
    videoId: null,
    name: '1. Авторизація',
    manualPath: 'authorization.md',
  },
  {
    pageId: '2',
    videoId: 'XDeeMzzdtm4',
    name: '2. Розділи меню кабінету лабораторії',
    manualPath: 'menu.md',
  },
  {
    pageId: '3',
    videoId: 'i2FupkBv6aE',
    name: '3. Замовлення покупця',
    manualPath: 'orders.md',
  },
  {
    pageId: '3-1',
    videoId: 'U1eRoXf3ris',
    name: '3.1 Як створити замовлення покупця',
    manualPath: null,
  },
  {
    pageId: '3-2',
    videoId: 'QEYCnfb1vb4',
    name: '3.2 Якщо контрагент не знайдено у першому полі',
    manualPath: null,
  },
  {
    pageId: '3-3',
    videoId: 'Q5674hG0-mY',
    name: '3.3 Як роздрукувати рахунок та договір до замовлення',
    manualPath: null,
  },
  {
    pageId: '3-4',
    videoId: 'nqwmOzA0khQ',
    name: '3.4 Якщо не всі колонки відображаються',
    manualPath: null,
  },
  {
    pageId: '3-5',
    videoId: '4O6dy2uHwDE',
    name: '3.5 Як редагувати замовлення',
    manualPath: null,
  },
  {
    pageId: '3-6',
    videoId: 'KNeYF2tDqmI',
    name: '3.6 Як видалити замовлення',
    manualPath: null,
  },
  {
    pageId: '4',
    videoId: 'EECELxaF4fc',
    name: '4. Акти',
    manualPath: null,
  },
  {
    pageId: '4-1',
    videoId: 'FAQaN900AwE',
    name: '4.1 Як роздрукувати акт',
    manualPath: null,
  },
  {
    pageId: '5',
    videoId: '9m1_0wqnWsU',
    name: '5. Замовлення знижки',
    manualPath: null,
  },
  {
    pageId: '5-1',
    videoId: 'CRZC-YHkb78',
    name: '5.1 Як замовити знижку',
    manualPath: null,
  },
];
